feat: Add lifecycle rules for GCS buckets
honestbank/terraform-gcp-gcs pull request #16
Opened 2023-06-13 10:17 UTC by sunilhonest

## Pull Request Submission Checklist

Please confirm that you have done the following before requesting reviews:

- [ ] I have confirmed that the PR type is appropriate for the change I am making according to the [Honest Pull Request and Commit Message Naming Conventions](https://www.notion.so/honestbank/Pull-Request-and-Commit-Message-Naming-Conventions-bd97f2cbb34c4c73b1ff3a3e384b850c).
- [ ] I have typed an adequate description that explains **why** I am making this change.
- [ ] I have installed and run standard pre-commit hooks that lints and validates my code.

### Description

Adds lifecycle rules for GCS buckets

2023-06-13 10:21 UTC, MXfive approved these changes

2023-06-13 11:47 UTC, bibek4699 requested changes

2023-06-13 11:47 UTC, bibek4699 commented on modules/gcp_gcs_bucket/main.tf
> +
remove this line

2023-06-14 02:11 UTC, sunilhonest commented on modules/gcp_gcs_bucket/main.tf
> +
Removed.

2023-06-14 02:12 UTC, bibek4699 approved these changes

2023-06-14 02:18 UTC, merged